#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "𝑇ℎ𝑒› َِ𝘢َِ𝙁َِ𝘠َِ𝘰َِ𝙉َِ𝘢 𝐸𝐿 𝐾𝑒𝐵𝑒𝑟 ,#'(مـغـلق)𖤐]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlbGV0aG9uQXJhYi9UZWxldGhvbkFyL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO == "-𝑇ℎ𝑒› َِ𝘢َِ𝙁َِ𝘠َِ𝘰َِ𝙉َِ𝘢 𝐸𝐿 𝐾𝑒𝐵𝑒𝑟 ,#'(مـغـلق)𖤐" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlbGV0aG9uQXJhYi9UZWxldGhvbkFyL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlbGV0aG9uQXJhYi9UZWxldGhvbkFyL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="iqthon.zip"
    echo "   تنزيل اكواد السورس ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  تنزيل تخزين السورس ..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "تم الانتهاء"
    rm -rf "$zippath"
    sleep 5
    cd $CATPATH
    echo "جـاري الاسـتراد لـتليثون افـــــيـــــونا  ..."
    echo "1
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
